project:
  type: book

book:
  title: "Statistics and Information Systems"
  author: "Mina Norouzirad, Miguel Fonseca, Gracinda Guerreiro"
  date: "7/11/2025"
  chapters:
    - index.qmd
    - part: "EDA"
      chapters: 
        - chapters/chapter1_data_ethics.qmd
        
        
bibliography: references.bib

format:
  html:
    theme: 
     - cosmo
    css: libs/style.css
    toc-depth: 4

