project:
  type: book

book:
  title: "Statistics and Information Systems"
  author: "Mina Norouzirad, Miguel Fonseca, Gracinda Guerreiro"
  date: "7/11/2025"
  chapters:
    - index.qmd
    - part: "EDA"
      chapters: 
        - chapters/chapter1_data_ethics.qmd
        - chapters/chapter3_dplyr.qmd
        - chapters/chapter2_data_visualization.qmd
        
bibliography: references.bib

# Set default options for every bookpage that may or may not include webR.
webr: 
  show-startup-message: false    # Disable displaying status of webR initialization

# Attach webR extension for the project
filters:
  - webr
  
format:
  html:
    theme: 
     - cosmo
    css: libs/style.css
    toc-depth: 4

